defmodule Column.WebhookHandler do
  @moduledoc """
  Behaviour and plug helper for handling incoming Column webhook deliveries.

  ## Usage with Plug/Phoenix

  Implement the `Column.WebhookHandler` behaviour in your handler module:

      defmodule MyApp.ColumnWebhookHandler do
        use Column.WebhookHandler,
          secret: System.get_env("COLUMN_WEBHOOK_SECRET")

        @impl Column.WebhookHandler
        def handle_event("transfer.ach.settled", payload, _meta) do
          transfer = payload["data"]
          MyApp.Payments.mark_settled(transfer["id"])
          :ok
        end

        def handle_event("transfer.ach.returned", payload, _meta) do
          MyApp.Payments.mark_returned(payload["data"]["id"])
          :ok
        end

        def handle_event(_type, _payload, _meta) do
          # Ignore unhandled events — always return :ok
          :ok
        end
      end

  Then add it to your router (Phoenix example):

      # router.ex
      post "/webhooks/column", MyApp.ColumnWebhookHandler, []

  Or use as a Plug in a pipeline:

      plug MyApp.ColumnWebhookHandler

  ## Behaviour callbacks

  Your module must implement:

  - `handle_event(type, payload, meta)` — called for each verified webhook.
    Return `:ok` to acknowledge, `{:error, reason}` to signal failure (Column
    will retry the delivery).

  ## Signature verification

  `use Column.WebhookHandler` injects plug pipeline code that:

  1. Reads the raw request body (before JSON parsing destroys byte-exactness)
  2. Validates the `column-signature` HMAC-SHA256 header
  3. Rejects with 401 if invalid
  4. Decodes the JSON body and dispatches to `handle_event/3`
  5. Returns 200 on `:ok`, 500 on `{:error, _}`

  **Important:** You must configure your Plug/Phoenix endpoint to cache raw
  body for webhook routes. In Phoenix:

      # endpoint.ex
      plug Plug.Parsers,
        parsers: [:urlencoded, :multipart, :json],
        pass: ["*/*"],
        body_reader: {MyApp.CacheBodyReader, :read_body, []},
        json_decoder: Phoenix.json_library()
  """

  @doc """
  Handle a verified Column webhook event.

  - `type` — the Column event type string, e.g. `"transfer.ach.settled"`
  - `payload` — the full decoded JSON payload map
  - `meta` — map with `:request_id` and `:delivery_id` keys
  """
  @callback handle_event(type :: String.t(), payload :: map(), meta :: map()) ::
              :ok | {:error, term()}

  defmacro __using__(opts) do
    quote do
      @behaviour Column.WebhookHandler

      @column_webhook_secret Keyword.get(unquote(opts), :secret)

      if is_nil(@column_webhook_secret) do
        raise ArgumentError,
              "#{__MODULE__}: use Column.WebhookHandler requires a :secret option. " <>
                "Pass `secret: System.get_env(\"COLUMN_WEBHOOK_SECRET\")`."
      end

      @doc false
      @spec init(keyword()) :: keyword()
      def init(options), do: options

      @doc false
      @spec call(map(), keyword()) :: map()
      def call(conn, _opts) do
        Column.WebhookHandler.__dispatch__(conn, __MODULE__, @column_webhook_secret)
      end

      defoverridable init: 1
    end
  end

  @doc false
  @spec __dispatch__(map(), module(), String.t()) :: map()
  def __dispatch__(conn, handler_module, secret) do
    # This function is called by the plug generated by `use Column.WebhookHandler`.
    # In a real Phoenix/Plug app, conn would be a %Plug.Conn{}.
    # We keep this dependency-free by working with a plain map contract.
    with {:ok, raw_body} <- get_raw_body(conn),
         signature when not is_nil(signature) <- get_signature(conn),
         :ok <- Column.Webhooks.verify_signature(raw_body, signature, secret),
         {:ok, payload} <- Jason.decode(raw_body) do
      type = payload["type"]

      meta = %{
        request_id: get_header_value(conn, "x-request-id"),
        delivery_id: get_header_value(conn, "column-delivery-id")
      }

      case handler_module.handle_event(type, payload, meta) do
        :ok ->
          send_response(conn, 200, "ok")

        {:error, reason} ->
          send_response(conn, 500, "handler error: #{inspect(reason)}")
      end
    else
      nil ->
        send_response(conn, 401, "missing column-signature header")

      :error ->
        send_response(conn, 401, "invalid signature")

      {:error, %{__exception__: true} = err} ->
        send_response(conn, 400, "invalid JSON: #{Exception.message(err)}")

      {:error, reason} ->
        send_response(conn, 500, "error: #{inspect(reason)}")
    end
  end

  # ---------------------------------------------------------------------------
  # Private — conn helpers (Plug-compatible but dependency-free)
  # ---------------------------------------------------------------------------

  @spec get_raw_body(map()) :: {:ok, binary()} | {:error, :no_raw_body}
  defp get_raw_body(%{assigns: %{raw_body: body}}) when is_binary(body), do: {:ok, body}
  defp get_raw_body(%{body_params: body}) when is_binary(body), do: {:ok, body}
  defp get_raw_body(_conn), do: {:error, :no_raw_body}

  @spec get_signature(map()) :: String.t() | nil
  defp get_signature(conn) do
    get_header_value(conn, "column-signature")
  end

  @spec get_header_value(map(), String.t()) :: String.t() | nil
  defp get_header_value(%{req_headers: headers}, name) when is_list(headers) do
    case List.keyfind(headers, name, 0) do
      {_, value} -> value
      nil -> nil
    end
  end

  defp get_header_value(_, _), do: nil

  @spec send_response(map(), non_neg_integer(), String.t()) :: map()
  defp send_response(conn, status, body) do
    Map.merge(conn, %{status: status, resp_body: body, halted: true})
  end
end
